#!/bin/bash
OUTPUT=accounts.txt
: > $OUTPUT

####################################
: > zipcode.txt
for ((i=1;i<=9;i++));do echo 6060$i >> zipcode.txt; done
for ((i=10;i<=19;i++));do echo 606$i >> zipcode.txt; done
#####################################

for i in `cat zipcode.txt`;do for j in `cat type.txt`;do echo VTI\_$i\_$j >> $OUTPUT;done;done

rm zipcode.txt
